Migrated blogs from old site to new django app (Envision project)
IEEE-NITK/corpus pull request #163
Opened 2024-08-17 11:47 UTC by UtsavBhamra

# Description

As part of envision project, I migrated all the blogs from the old jekyll site to a new django app.

Fixes # (issue)

## Dependencies

markdown v3.6

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ x ] My code follows the style guidelines of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes

2024-08-19 14:36 UTC, yukitya-1811 requested changes

2024-09-06 20:36 UTC, yukitya-1811 commented on corpus/blog/models.py
> +    author_github = models.CharField(max_length=70, blank=True)
Can we not use a URL field instead?

2024-11-28 10:36 UTC, yukitya-1811 approved these changes

2024-12-06 06:15 UTC, yukitya-1811 approved these changes

2024-12-06 06:21 UTC, anirudhprabhakaran3 approved these changes

2024-12-06 06:33 UTC, merged