Profile page Modifications
IEEE-NITK/corpus pull request #192
Opened 2024-12-26 12:56 UTC by CodePokeX

# Description

Made modifications to Pull Request #164 to link the blog page to the profile page. 

Fixes #26 

## Dependencies

List any dependencies that are required for this change.

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

- [ ] Test A
- [ ] Test B

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2025-01-21 14:46 UTC, yukitya-1811 approved these changes

2025-01-21 15:26 UTC, yukitya-1811 commented on corpus/accounts/forms.py
> +class UserForm(forms.ModelForm):
instead of `forms.ModelForm`, try using `CorpusModelForm` instead. It is defined in the application somewhere

2025-01-21 15:26 UTC, yukitya-1811 commented on corpus/accounts/forms.py
> +class ExecutiveMemberForm(forms.ModelForm):
same here as above

2025-01-21 15:27 UTC, yukitya-1811 commented on corpus/accounts/forms.py
> +        widgets = {
if you use `CorpusModelForm` then you won't have to worry about styling the widgets individually as it will take care of all the styling on its own

2025-01-21 15:32 UTC, yukitya-1811 commented on corpus/accounts/views.py
> +        executive_member = ExecutiveMember.objects.get(roll_number=roll_no, user=user)
What happens if a user tries going to the edit view of some other executive member? In that case we should return a `forbidden` response

2025-01-21 15:34 UTC, yukitya-1811 commented on corpus/accounts/views.py
> +            executive_member_form = ExecutiveMemberForm()
continuing from the last comment, here if there's no `executive_member` you're essentially loading a blank form, which should not happen. If someone messes with the URL and tries accessing another executive member's profile, it should forbid them from doing so (or redirect them to their own profile page instead with a warning)

2025-01-22 16:29 UTC, CodePokeX commented on corpus/accounts/forms.py
> +        widgets = {
I am using only 'required': True to add necessary fields features

2025-01-23 17:31 UTC, anirudhprabhakaran3 requested changes

2025-01-23 17:31 UTC, anirudhprabhakaran3 commented on corpus/accounts/views.py
> +        raise PermissionDenied("You are not authorized to edit this profile.")
This is not the correct error to raise here. Should raise a 404 or something.
Also, directly use `get_object_or_404` for getting the ExecutiveMember without using this try clause.

2025-01-23 17:35 UTC, CodePokeX commented on corpus/accounts/views.py
> +        raise PermissionDenied("You are not authorized to edit this profile.")
I was trying to use this for validation. Since user is the currently logged in user and executive_member is the one's whose edit_profile is being accessed. So only if user has the same roll_no as the one whose edit_profile is being requested then only the page would be loaded. Thus I went for 403 instead of 404.

2025-01-23 17:58 UTC, CodePokeX commented on corpus/accounts/views.py
> +        raise PermissionDenied("You are not authorized to edit this profile.")
Also get_object_or_404 will redirect me to the 404 page if the fetch comes false whereas I want to redirect to the dashboard giving a warning. Thus I used the try clause.

2025-01-24 04:52 UTC, anirudhprabhakaran3 commented on corpus/accounts/views.py
> +        raise PermissionDenied("You are not authorized to edit this profile.")
Oh okay got it. I think I misunderstood the query then, now it looks correct. This does look fine yeah sure.

2025-01-26 07:34 UTC, anirudhprabhakaran3 requested changes

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/forms.py
> +        widgets = {
You don't need to do that right? Since it is a model form, if the values are required in the DB, the form will automatically mark them as required in the UI as well.

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/models.py
> +from corpus.validators import validate_image
nit: did you run the linter? Looks like this style would have been picked up by that.

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/models.py
> +    hide_linkedin = models.BooleanField(default=False, null=True, blank=True)
For booleans, don't allow null and blank values. The default should be False, and let them opt in to true.

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/urls.py
> +    path("profile/edit/<roll_no>", edit_profile, name="edit_profile")
Follow `/resource/id/action` styles for URLs. So, the edit URL would be `/profile/201EC106/edit`

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/views.py
> +# from .models import User
Remove this if not needed

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/accounts/views.py
> +                executive_member.hide_github = False
Why is this needed? Doesn't the form saving directly work?

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/templates/accounts/edit_profile.html
> +            const maxFileSize = 5 * 1024 * 1024;
Move this file size to a constant in some python code, and use that throughout the project. Make like a file called `corpus/constants.py` and define `MAX_IMAGE_SIZE`, and pass that everywhere, including in functions and templates.

in case we need to increase/decrease this in the future, we don't have to hunt down every use instance and update it.

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/templates/accounts/edit_profile.html
> +                        alert("File size is too big. Please upload a file smaller than 2MB.");
Isn't the defined value 5MB xD

2025-01-26 07:34 UTC, anirudhprabhakaran3 commented on corpus/templates/accounts/edit_profile.html
> +    <script>
We have jQuery right? Use that over traditional JS, much easier for us to future-proof and maintain

2025-01-29 02:10 UTC, anirudhprabhakaran3 commented on corpus/accounts/urls.py
> +            "/password_reset_email.html"
I'm guessing something went wrong here? Remove this change if not needed

2025-01-29 02:10 UTC, anirudhprabhakaran3 commented on corpus/constants.py
> +        raise ValidationError("Image size exceeds 5MB.")
Remove this. Constants should only have the actual constant variables, no functions. Having the function in validators is correct

2025-01-29 02:54 UTC, CodePokeX commented on corpus/accounts/urls.py
> +            "/password_reset_email.html"
The linter is throwing line size exceeded. So I did this. Can I anyhow exclude this from the linter?

2025-01-29 12:56 UTC, anirudhprabhakaran3 commented on corpus/accounts/urls.py
> +            "/password_reset_email.html"
hmm....does the string work properly?

2025-01-29 15:08 UTC, CodePokeX commented on corpus/accounts/urls.py
> +            "/password_reset_email.html"
Yeah this works. Anyways I have made the commit by ignoring the linter and making it as a single string.

2025-02-13 11:22 UTC, merged