Added accounts and login features
IEEE-NITK/corpus pull request #29
Opened 2023-09-20 10:53 UTC by anirudhprabhakaran3

# Description

Adds accounts and login to Corpus.

Fixes #18, #19

## Dependencies

None

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

- [ ] Test A
- [ ] Test B

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-09-21 09:55 UTC, anirudhprabhakaran3 commented
Oh I have to add tests for accounts. Will do that over this week and weekend.

2023-09-21 11:10 UTC, nishant-nayak commented
Convert your PR to draft if tests are pending to be added.

2023-11-09 18:02 UTC, nishant-nayak requested changes
Left a bunch of comments, mostly styling related.

Logic wise code seems alright, if you're stuck on styling let me know and I'll try pitching in some code.

2023-11-09 18:02 UTC, nishant-nayak commented on corpus/templates/accounts/login.html
> +<div class="card w-1/2 mx-auto my-10 bg-base-100 glass shadow-xl prose">
Not really a fan of the glass theme here as well, I think you can take reference from popular website login pages (LeetCode is a good example) to style the page better.

2023-11-21 17:09 UTC, anirudhprabhakaran3 commented on corpus/accounts/tests.py
> +        self.assertEqual(response.status_code, 200)
Apparently this is what Django returns. Even the server logs return a 200.

https://stackoverflow.com/questions/25839434/django-login-with-wrong-credentials-returns-200-not-401

2023-11-21 19:07 UTC, anirudhprabhakaran3 commented on corpus/templates/accounts/signup.html
Regarding the phone number thing - does that like apply for international numbers also? That's why I didn't put anything there for now 😅

2023-11-25 06:24 UTC, nishant-nayak commented on corpus/accounts/tests.py
> +        self.assertEqual(response.status_code, 200)
Interesting. I suppose this is fine as long as this is the standard we maintain.

2023-11-25 06:25 UTC, nishant-nayak commented on corpus/accounts/tests.py
> +        self.assertEqual(response.status_code, 200)
Interesting. I suppose this is fine as long as this is the standard we maintain.

2023-11-25 06:29 UTC, nishant-nayak commented on corpus/templates/accounts/signup.html
I suppose we can have some other kind of validation in place for phone numbers. I just learnt the shortest phone numbers can be like 7-8 digits xD

2023-11-25 07:24 UTC, nishant-nayak approved these changes
LGTM!

2023-11-25 07:25 UTC, merged