Setup JS toolchain for Tailwind and DaisyUI
IEEE-NITK/corpus pull request #69
Opened 2023-12-25 12:30 UTC by anirudhprabhakaran3

# Description

Setup JS toolchain for Tailwind and DaisyUI.

Fixes # (issue)

## Dependencies

List any dependencies that are required for this change.

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration. (for bug fix / breaking change)
_Put an `x` in the boxes that apply_

- [ ] Test A
- [ ] Test B

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-12-26 14:33 UTC, nishant-nayak commented
Is this something we want to add to dev environments? I definitely see the benefit in adding this toolchain for production releases, but unless there's a way to "hot reload" the Tailwind CSS definitions each time a change is made to frontend code I don't think we should add this to the development toolchain.

2023-12-26 18:48 UTC, anirudhprabhakaran3 commented
Aah yes, there is. In the README instrucetion given, instead of using `--minify` we just have to use `--watch` and it will automatically reload everything.

2024-01-09 17:09 UTC, nishant-nayak requested changes
Update the README, I think the change itself works as expected. Nice addition!

2024-01-09 17:09 UTC, nishant-nayak commented on README.md
> +2. You'll need to setup the JS Toolchain, so that Tailwind and DaisyUI work properly. Install the version of `node`
This is no longer relevant right? Update the docs accordingly. Mention that for Windows, this hot reloading only works with WSL. For non-WSL, I think they can either use these steps itself, or restart the container on each change.

2024-01-12 12:13 UTC, nishant-nayak approved these changes
LGTM!

2024-01-12 12:14 UTC, merged