Added Dockerfile and docker-compose
IEEE-NITK/corpus pull request #7
Opened 2023-01-13 14:34 UTC by anirudhprabhakaran3

# Description

Adds Dockerfiles and Docker Compose to project, so that people can develop from anywhere.

Fixes #4 

## Dependencies

Docker is required on system.

## Type of Change

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Have run `docker compose up` on my local system, and the deploymet works properly.

---

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-01-14 11:06 UTC, nishant-nayak requested changes
Add documentation in the `README.md` of this repository on the steps to set up this project using Docker Compose.

2023-01-14 11:06 UTC, nishant-nayak commented on corpus/corpus/settings.py
> +ALLOWED_HOSTS = ["*"]
Update this to allow only the required hosts. You can include some logic like:
```python
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1",]
else:
    ALLOWED_HOSTS = ["URL Of Deployment"]
```

2023-01-14 11:06 UTC, nishant-nayak commented on corpus/corpus/settings.py
>  DATABASES = {
Values in this dict should not be hardcoded. Move them out into environment variables. Only the `ENGINE` can stay hardcoded.

2023-02-26 19:57 UTC, nishant-nayak commented
@anirudhprabhakaran3 the new changes are making the test build fail. Please make the necessary changes to the GitHub action as well.

2023-02-27 07:10 UTC, anirudhprabhakaran3 commented
Yup, will check 👍🏻

2023-03-17 03:44 UTC, nishant-nayak approved these changes
LGTM!

2023-03-17 03:44 UTC, merged